version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    networks:
      - schoolapi-mynetwork

  db:
    image: postgres:14.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: schoolapi@123
      POSTGRES_USER: user-schoolapi
      POSTGRES_DB: schoolapi
    networks:
      - schoolapi-mynetwork

volumes:
  postgres-data:

networks:
  schoolapi-mynetwork:
